export { Home } from './Home'
export { ListExercises } from './AdminExercises/List'
export { Exercise } from './Exercise'
export { Login } from './Login'
export { notFound } from './NotFound'
export { CreateOrEditExercise } from './AdminExercises/CreateOrEdit'
export { ListCategories } from './AdminCategories/List'
export { CreateOrEditCategory } from './AdminCategories/CreateOrEdit'
